Solution
mate-academy/py-cinema-full-stack pull request #224
Opened 2023-12-13 16:04 UTC by vshvanska

![full](https://github.com/mate-academy/py-cinema-full-stack/assets/141127161/2f5360ad-3d21-4440-b48b-821a29e2dbe1)
![full_actors](https://github.com/mate-academy/py-cinema-full-stack/assets/141127161/98f20026-8aba-4f8d-af60-51ffcbd0a4ac)
![full_add_actor](https://github.com/mate-academy/py-cinema-full-stack/assets/141127161/ebd78124-7f44-4637-b805-d61c4ca94af4)
![full_cinemahalls](https://github.com/mate-academy/py-cinema-full-stack/assets/141127161/e231cc7f-9450-49cf-964f-05dd25eaaf80)
![full_genres](https://github.com/mate-academy/py-cinema-full-stack/assets/141127161/f5f26d2e-6895-48a2-bb01-db52d8091627)
![full_homepage](https://github.com/mate-academy/py-cinema-full-stack/assets/141127161/819e6c3f-a3a7-4e1e-af5d-94797159c830)
![full_moviedetail](https://github.com/mate-academy/py-cinema-full-stack/assets/141127161/18e40afd-3a8e-4863-8873-0647c2faa5bc)
![full_moviesession](https://github.com/mate-academy/py-cinema-full-stack/assets/141127161/15eb6848-b6e9-4d48-8739-95f9596b0d8b)
![full1](https://github.com/mate-academy/py-cinema-full-stack/assets/141127161/83db3092-5aad-4492-a770-6bfc6b46b477)

2023-12-13 21:32 UTC, RVChornyy approved these changes

2023-12-15 17:41 UTC, Y-Havryliv requested changes

2023-12-15 17:41 UTC, Y-Havryliv commented on frontend/src/views/ActorListScreen.vue
>            headers: { Authorization: `Bearer ${this.token}` }
what about posting actors?

2023-12-15 17:41 UTC, Y-Havryliv commented on frontend/src/views/MovieAddScreen.vue
> +          await axios.post(`/api/cinema/movies/${movie.id}/upload-image/`, data, imageConfig);
does it work correctly?

2023-12-15 17:41 UTC, Y-Havryliv commented on frontend/src/views/MovieDetailsScreen.vue
> +        const { data: movie } = await this.axios.get(`${import.meta.env.VITE_API_URL}/api/cinema/movies/${id}`, {
```suggestion
        const { data: movie } = await this.axios.get(`${import.meta.env.VITE_API_URL}/api/cinema/movies/${id}/`, {
```

2023-12-15 17:41 UTC, Y-Havryliv commented on frontend/src/views/MovieSessionDetailsScreen.vue
> +        const { data: session } = await this.axios.get(`${import.meta.env.VITE_API_URL}/api/cinema/movie_sessions/${id}`, {
```suggestion
        const { data: session } = await this.axios.get(`${import.meta.env.VITE_API_URL}/api/cinema/movie_sessions/${id}/`, {
```

2023-12-18 09:34 UTC, NEkropo1 requested changes

2023-12-18 09:34 UTC, NEkropo1 commented on backend/cinema/serializers.py
> +            data["movie_session"].cinema_hall, ValidationError
keep same styling in whole code, please.

2023-12-18 09:34 UTC, NEkropo1 commented on backend/sample_cinema.json
> +]
add newline everywhere

2023-12-19 18:31 UTC, wQuelS approved these changes
GJ

2025-01-27 18:03 UTC, closed without merging