Develop
mate-academy/py-cinema-full-stack pull request #342
Opened 2024-06-23 18:42 UTC by AlexTsikhun

![image](https://github.com/mate-academy/py-cinema-full-stack/assets/83775762/accdaa38-cf49-4bc5-8259-0a5cd5a22f65)

![image](https://github.com/mate-academy/py-cinema-full-stack/assets/83775762/13cb3116-6ea3-4be1-801b-c573c057711c)
![image](https://github.com/mate-academy/py-cinema-full-stack/assets/83775762/d09b95bb-31bf-45bc-b66d-17586c13b0a9)

![image](https://github.com/mate-academy/py-cinema-full-stack/assets/83775762/e1167d17-b2d4-48f1-93c7-e29420127b87)

2024-06-24 06:14 UTC, vsmutok requested changes
Also Please attach screenshots where it is clearly visible that the photo is displayed correctly on the website.

2024-06-24 06:14 UTC, vsmutok commented on .env.sample
Why you remove this file?

2024-06-24 06:14 UTC, vsmutok commented on frontend/.env.sample
Why you remove this file?

2024-06-26 05:47 UTC, AlexTsikhun commented
![image](https://github.com/mate-academy/py-cinema-full-stack/assets/83775762/4d648924-6056-4b65-a838-430064294e60)

2024-06-26 06:13 UTC, vsmutok approved these changes
Great!

2026-05-17 09:59 UTC, closed without merging