Develop
mate-academy/py-cinema-full-stack pull request #367
Opened 2024-08-12 08:51 UTC by AlexGrytsai

![1](https://github.com/user-attachments/assets/8621cc9d-48b7-408b-88a4-104128150662)
![2](https://github.com/user-attachments/assets/b644a546-b261-4af5-b19b-c90e6c60d2d7)
![3](https://github.com/user-attachments/assets/7246fa01-dc72-4893-8b3b-d0f513a74b37)
![4](https://github.com/user-attachments/assets/cd29c7eb-1348-42af-ad35-a8ea89e9d638)
![5](https://github.com/user-attachments/assets/093894e9-5f72-44b5-b521-456338a8b1db)
![6](https://github.com/user-attachments/assets/ed47246b-5831-4115-93f9-d4815d15293f)
![7](https://github.com/user-attachments/assets/dbc2ea94-47a0-4650-bc93-1a6928a09b6d)
![8](https://github.com/user-attachments/assets/2ccbd29b-16a0-4d76-86af-aeb3818b0e6b)
![9](https://github.com/user-attachments/assets/ef36d81a-2cfe-4ac3-b2b7-d9f51e940397)
![10](https://github.com/user-attachments/assets/b2880060-5097-4765-91a5-a5464747e8be)
![11](https://github.com/user-attachments/assets/47011b35-0834-497b-ac9d-d35278e6cba9)

2024-08-12 16:25 UTC, YukihiroSM reviewed
Image uploading URL is not fixed. 
![image](https://github.com/user-attachments/assets/50e6549c-8a9d-4d32-bb3e-0a9f687641be)

2024-08-12 16:25 UTC, YukihiroSM requested changes
Comment before.

2024-08-13 11:33 UTC, AlexGrytsai commented
![12](https://github.com/user-attachments/assets/f8621eeb-2ffc-484a-b4ff-c898441a4eb4)
![13](https://github.com/user-attachments/assets/9efe611b-879a-4d01-a622-4d7abcec0cc4)

2024-08-13 14:05 UTC, vasylhnatiuk approved these changes

2024-10-08 04:50 UTC, closed without merging